### ISSUE TITLE
resolving the warehouse index url for a download link

### ISSUE THREAD

**Issue by jku** [jku/pip#3]
we need to be able to tell if a distribution download url should be downloaded with TUF or not -- in practice that means we need to know which repository gave us this URL (to then check if the repository is TUF-enabled).

The pip data structure that provides the download URL is `Link`. There is a `Link.comes_from` which contains the URL of the index file that the download URL was parsed from (in other words the 'project directory'). Current plan is to resolve comes_from to Warehouse index url by backing up one level:

`    urllib.parse.urljoin("https://pypi.org/simple/django/", "..") # 'https://pypi.org/simple/'
`

Would be good to confirm that this is safe to do WRT warehouse index structure: failing to resolve correctly here would mean silently disabling TUF for the download. 

Alternative -- and this might be a safer choice -- would be to modify `Link` to contain the index url explicitly.

**Comment by woodruffw** [comment]
> Would be good to confirm that this is safe to do WRT warehouse index structure: failing to resolve correctly here would mean silently disabling TUF for the download.

This should always be safe on Warehouse, unless I'm missing something. It might also be good to **not** silently disable TUF for downloads from particular domains (namely `pypi.org`) -- failure for whatever reason to retrieve TUF from PyPI itself should perhaps be treated as a special case and a hard failure.

**Comment by jku** [comment]
Thanks, good to know. I think I'll still try to solve this in a defensive way if possible: store the actual index_url with the Link (distribution download URL). future architecture changes shouldn't then be able to affect it.

I agree on hard coding an additional pypi.org check and I have that in my implementation notes already: that should help with noticing any future pip code (or warehouse api) changes that could break TUF usage as well...

**Comment by jku** [comment]
I'm closing this and considering the approach described to be enough (removing one level from project url is the index url)
