### ISSUE TITLE
resolving TUF target name from distribution download URL

### ISSUE THREAD

**Issue by jku** [jku/pip#6]
A design goal is to minimize the required client configuration. In practice I'm hoping I won't have to store package base directory ('packages/' on files.pythonhosted.org) in the configuration.

The plan is to integrate tuf into pip in a place where we get a Link object which contains among other things  the full url of the file to be downloaded and helper properties for parsing it. The issue is **how to extract the TUF metadata name from the url?**

Example URL:

    https://files.pythonhosted.org/packages/ca/ab/5e004afa025a6fb640c6e983d4983e6507421ff01be224da79ab7de7a21f/Django-3.0.8-py3-none-any.whl#sha256=5457fc953ec560c5521b41fad9e6734a4668b7ba205832191bbdff40ec61073c

We want to extract

    ca/ab/5e004afa025a6fb640c6e983d4983e6507421ff01be224da79ab7de7a21f/Django-3.0.8-py3-none-any.whl

* With knowledge of base package directory this is easy... Should warehouse include that info in custom metadata? or can we just assume it's always "packages/"?
* Another option is to define that _Metadata name is the filename without fragments with enough preceding path components to form the hash_: this assumes we know how long the hash is (either warehouse must to tell us or we are not future proof for hash length changes)
* Alternatively define that _Metadata name is the filename without fragments with 3 preceding directories_ -- this is not great for future proofing (but I have no idea if the three directory levels could in practice become too few in the future)

**Comment by jku** [comment]
The unstated basic assumption here is: I'm trying to avoid configuring the mirror host or the base path (in this case 'packages/') in the client. If I knew the base path, parsing the metadata name would be easy.

**Comment by woodruffw** [comment]
> * _Metadata name is the filename without fragments with enough preceding path components to form the hash_: this assumes we know how long the hash is (either warehouse must to tell us or we are not future proof for hash length changes)

This sounds _reasonable_ to me -- it's unlikely that Warehouse will be moving away from BLAKE2b anytime soon, so this _could_ just be a constant that's baked into pip. Then again, it certainly would make migrating a pain, should that ever need to occur. But I expect that such a migration would require a total turnover of the package index links anyways, so perhaps that's not a big deal.

**Comment by jku** [comment]
> Then again, it certainly would make migrating a pain, should that ever need to occur. But I expect that such a migration would require a total turnover of the package index links anyways, so perhaps that's not a big deal.

In the very unlikely event of hash change happening, the worst outcome is that clients that did not upgrade in time would have to use "--disable-package-security" (or whatever it will be called) once to upgrade pip... so maybe this is reasonable

For now, I'll work with the assumption that _Metadata name is the filename without fragments with enough preceding path components to form a 256-bit blake2b hash_. Thanks for reply.

**Comment by jku** [comment]
Current implementation is _metadata name is filename plus 3 preceding directory names_ -- but there is a sanity check to ensure the result has the correct length.

I'm closing this but keeping a note to mention it in review
